version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: meetings
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/meetings
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://cornercase:123456@db:5432/meetings
    env_file:
      - ./.env.dev
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cornercase
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=meetings
    ports:
      - 5432:5432

volumes:
  postgres_data: